version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db01
      WORDPRESS_DB_USER: docker
      WORDPRESS_DB_PASSWORD: N0obp@wnr!
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: docker
      MYSQL_PASSWORD: N0obp@wnr!
      MYSQL_RANDOM_ROOT_PASSWORD: '1'