# TODO: Update ports on each services.
# TODO: Update individual download directories.

version: '3'

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /data/Sync/docker/sonarr:/config
      - /data/Media/Plex/Shows:/tv
      - /data/Media/transmission/downloads:/downloads
    ports:
      - 91:8989
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 92:9117
    volumes:
      - /data/Sync/docker/jackett/config:/config
      - /data/Media/jackett/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /data/Sync/docker/radarr:/config
      - /data/Media/Plex/Movies:/movies
      - /data/Media/radarr/downloads:/downloads
    ports:
      - 93:7878
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /data/Sync/docker/lidarr:/config
      - /data/Media/Plex/Music:/music
      - /data/Media/lidarr/downloads:/downloads
    ports:
      - 94:8686
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /data/Sync/docker/transmission:/config
      - /data/Media/transmission/downloads:/downloads
      - /data/Media/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
